### ISSUE TITLE
Troubleshooting Kerberos connection to Impala

### ISSUE THREAD

**Issue by acassaigne** [cloudera/thrift_sasl#11]
Hi,

Maybe I'm hitting a bug with thrift-sasl-0.3.0 when I try to connect to Impala with a kerberos token. 
I got this error with instanciation on connect  object.
For the following connect statement:
connect(host='host_impala', port=21050, auth_mechanism='GSSAPI', database='my_db', kerberos_service_name='impala')

My script return 
Traceback (most recent call last):
  File "c.py", line 2, in <module>
    conn = connect(host='bda1node05.int.adeo.com', port=21050, auth_mechanism='GSSAPI', database='dataiku', kerberos_service_name='impala')
  File "/usr/lib/python3.4/site-packages/impala/dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "/usr/lib/python3.4/site-packages/impala/hiveserver2.py", line 758, in connect
    transport.open()
  File "/usr/lib/python3.4/site-packages/thrift_sasl/__init__.py", line 67, in open
    if not self._trans.isOpen():
AttributeError: 'TSocket' object has no attribute 'isOpen'

The version used is: 
Name: thrift-sasl
Version: 0.3.0
Summary: Thrift SASL Python module that implements SASL transports for Thrift (`TSaslClientTransport`).
Home-page: https://github.com/cloudera/thrift_sasl
Author: Wes McKinney
Author-email: wes@cloudera.com
License: Apache License, Version 2.0
Location: /usr/lib/python3.4/site-packages
Requires: sasl, thrift

But I havn't any problem with 0.2.1 version:
pip3 install thrift_sasl==0.2.1
Collecting thrift_sasl==0.2.1
Requirement already satisfied: sasl>=0.2.1 in /usr/lib64/python3.4/site-packages (from thrift_sasl==0.2.1)
Requirement already satisfied: thriftpy in /usr/lib64/python3.4/site-packages (from thrift_sasl==0.2.1)
Requirement already satisfied: six in /usr/lib/python3.4/site-packages (from sasl>=0.2.1->thrift_sasl==0.2.1)
Requirement already satisfied: ply<4.0,>=3.4 in /usr/lib/python3.4/site-packages (from thriftpy->thrift_sasl==0.2.1)
Installing collected packages: thrift-sasl
  Found existing installation: thrift-sasl 0.3.0
    Uninstalling thrift-sasl-0.3.0:
      Successfully uninstalled thrift-sasl-0.3.0
Successfully installed thrift-sasl-0.2.1

And my script work fine.

**Comment by icolombi** [comment]
I can confirm the exact same problem: with thrift-sasl-0.3.0 I'm unable to connect to Impala, it works with 0.2.1.

Python 3.5.2 on CentOS 6.10 here.

**Comment by biocar2001** [comment]
hi,

Here there is a problem. When I am working with the connection of impyla with impala and kerberos, with the version of thrift-sasl-0.3.0 I get the error:

AttributeError: 'TSocket' object has no attribute 'isOpen'

If I upgrade to 0.2.1 everything is OK, but I have other problem, the connection with hive and kerberos doesnt work and I need the version 0.3.0 because in the previous version tell me:

method readall doesnt exist.

What Can I do for both versions works?
Thanks in advance

**Comment by dknupp** [comment]
Should have been fixed by https://github.com/cloudera/thrift_sasl/pull/13
